services:
  a:
    build:
      context: ./server8001
    environment:
      - ipA2B=b
      - pageA=<h1>8001</h1>
    ports:
      - "8001:8001"
  b:
    build:
      context: ./server7001
    environment:
      - pageB=<h1>7001</h1>
    ports:
      - "7001:7001"
